project:
  type: website
  output-dir: docs
  render:
   - "*.qmd"
   - "!pkg/"

exectute:
  freeze: auto

website:
  site-url: "https://dbetebenner.github.io/Modelling_Heteroskedasticity/"
  repo-url: "https://github.com/dbetebenner/Modelling_Heteroskedasticity"
  title: "Modelling non-linear, heteroskedastic data using R"
  repo-actions: [edit, issue]
  favicon: ./images/cfa_logo_color.png

  # navigation
  page-navigation: true
  navbar:
    title: "Modelling Heteroskedasticity"
    logo: ./images/cfa_logo_grey.png
    logo-href: "https://dbetebenner.github.io/Modelling_Heteroskedasticity"
    search: false
    pinned: true
    foreground: "#7c7c7c"
    right:
      - icon: github
        aria-label: github
        href: https://github.com/dbetebenner/Modelling_Heteroskedasticity
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/dbetebenner

  search:
    location: navbar
    type: overlay
    copy-button: true

  #footer
  page-footer:
    center:
      - icon: github
        text: GitHub
        aria-label: github
        href: https://https://github.com/dbetebenner/Modelling_Heteroskedasticity

  #socials
  open-graph: true
  twitter-card: 
    creator: "@dbetebenner"
    site: "@nciea1"

format:
  html:
    theme:
     - cosmo
     - ./css/custom.scss
    css: ./css/styles.css
    toc: true
    include-after: |
      <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:400,600" rel="stylesheet" type="text/css">
      <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <script type="text/javascript" src="/js/jquery.sticky-kit.min.js"></script>
      <script type="text/javascript" src="/js/scroll.js"></script>
